TASK: CGM-5096 create custom Link
punktDeForks/Sitegeist.Archaeopteryx pull request #1
Opened 2022-08-15 16:07 UTC by FahimNsr

2022-08-23 11:42 UTC, andrehoffmann30 commented
Hi @FahimNsr I miss the compiled plugin code in your PR. You need the commit the compiled plugin code otherwise your changes will not be use, when this package is installed in a project. Please the missing code changes. Thank you.

2022-08-23 12:56 UTC, andrehoffmann30 requested changes
I think the naming is not good here. `Custom` as the only naming information is meaningless. Something like `CustomLink` or `VariableLink` is better. Please think about what type of links your changes allow and choose a meaningful naming.

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/de/LinkTypes/Custom.xlf
> +                <target>Beliebige Link</target>
```suggestion
                <target>Beliebiger Link</target>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/de/LinkTypes/Custom.xlf
> +                <target>Beliebige Link:</target>
```suggestion
                <target>Beliebiger Link:</target>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/de/LinkTypes/Custom.xlf
> +                <source>enter text here</source>
```suggestion
                <source>Enter your text here</source>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/de/LinkTypes/Custom.xlf
> +                <target>Hier Text eingeben</target>
```suggestion
                <target>Hier ihren Text eingeben</target>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/de/LinkTypes/Custom.xlf
> +                <source>this field is required</source>
```suggestion
                <source>This field is required</source>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/en/LinkTypes/Custom.xlf
> +                <source>enter text here</source>
```suggestion
                <source>Enter your text here</source>
```

2022-08-23 12:56 UTC, andrehoffmann30 commented on Resources/Private/Translations/en/LinkTypes/Custom.xlf
> +                <source>this field is required</source>
```suggestion
                <source>This field is required</source>
```

2022-08-24 05:19 UTC, FahimNsr commented
Hi André, I added compiled File, and also as you mentioned, I changed the variable's name to customLink.

2022-08-26 11:27 UTC, andrehoffmann30 approved these changes

2022-08-26 11:27 UTC, merged